// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zearqegowhioaeymqdry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYXJxZWdvd2hpb2FleW1xZHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODI4NDMsImV4cCI6MjA3NDY1ODg0M30.cx-itZn0dqJ7emJNchC7TW_5lYupNu4wY9qBacCx5RY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});